// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.Repository;

#nullable disable

namespace NLayer.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220425132013_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.Core.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kalemler"
                        },
                        new
                        {
                            id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kitaplar"
                        },
                        new
                        {
                            id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Defterler"
                        });
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7030),
                            Name = "Kalem 1",
                            Price = 100m,
                            Stock = 20
                        },
                        new
                        {
                            id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7044),
                            Name = "Kalem 2",
                            Price = 180m,
                            Stock = 20
                        },
                        new
                        {
                            id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7045),
                            Name = "Kalem 3",
                            Price = 120m,
                            Stock = 70
                        },
                        new
                        {
                            id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7046),
                            Name = "Kitap 1",
                            Price = 145m,
                            Stock = 35
                        },
                        new
                        {
                            id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7047),
                            Name = "Kitap 2",
                            Price = 230m,
                            Stock = 70
                        },
                        new
                        {
                            id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7048),
                            Name = "Kitap 3",
                            Price = 180m,
                            Stock = 290
                        },
                        new
                        {
                            id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7049),
                            Name = "Defter 1",
                            Price = 500m,
                            Stock = 340
                        },
                        new
                        {
                            id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7050),
                            Name = "Defter 2",
                            Price = 300m,
                            Stock = 45
                        },
                        new
                        {
                            id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 4, 25, 16, 20, 13, 699, DateTimeKind.Local).AddTicks(7051),
                            Name = "Defter 3",
                            Price = 50m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("NLayer.Core.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Kırmızı",
                            Height = 20,
                            ProductId = 1,
                            Width = 20
                        },
                        new
                        {
                            Id = 2,
                            Color = "Yeşil",
                            Height = 40,
                            ProductId = 2,
                            Width = 30
                        });
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.HasOne("NLayer.Core.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayer.Core.ProductFeature", b =>
                {
                    b.HasOne("NLayer.Core.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.Core.ProductFeature", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NLayer.Core.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.Core.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
